// using System;
// using System.ComponentModel.DataAnnotations;
// using System.ComponentModel.DataAnnotations.Schema;
// using System.Diagnostics.CodeAnalysis;
// using Microsoft.AspNetCore.Mvc;


// namespace cmedcc_idass.backend.Models;
//     public class User
//     {
//         // The [Key] attribute designates this property as the primary key.
//         // The [DatabaseGenerated(DatabaseGeneratedOption.Identity)] attribute is often used for identity columns, though uniqueidentifier is typically generated by the application or a default value.
//         [Key]
//         public Guid UserId { get; set; }

//         [Required] // This attribute indicates that the column does not allow nulls.
//         [MaxLength(256)] // Specifies the maximum length of the string data.
//         public string Username { get; set; }

//         [Required]
//         [MaxLength(256)]
//         public string Email { get; set; }

//         [Required]
//         public string PasswordHash { get; set; }

//         [Required]
//         [NotNull]
//         public string Salt { get; set; }

//         // 'bit' in SQL Server maps to a 'bool' in C#.
//         public bool? IsActive { get; set; }

//         // 'datetime' in SQL Server maps to 'DateTime' in C#.
//         public DateTime CreatedAt { get; set; }

//         public DateTime? UpdatedAt { get; set; }

//     }